config/routes.rb
EnglishTrainer::Application.routes.draw do
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users

  resources :dictionaries

  resources :words

  root :to => "words#index"

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  validates_presence_of :name
  has_many :words
  belongs_to :user
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  # GET /dictionaries
  # GET /dictionaries.xml
  before_filter :require_user
  def index
    @dictionaries = current_user.dictionaries.paginate :page => params[:page], :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dictionaries }
    end
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.xml
  def show
    @dictionary = current_user.dictionaries.find(params[:id])
    @words = @dictionary.words.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dictionary }
    end
  end

  # GET /dictionaries/new
  # GET /dictionaries/new.xml
  def new
    @dictionary = current_user.dictionaries.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dictionary }
    end
  end

  # GET /dictionaries/1/edit
  def edit
    @dictionary = current_user.dictionaries.find(params[:id])
  end

  # POST /dictionaries
  # POST /dictionaries.xml
  def create
    @dictionary = current_user.dictionaries.new(params[:dictionary])

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to(@dictionary, :notice => 'Dictionary was successfully created.') }
        format.xml  { render :xml => @dictionary, :status => :created, :location => @dictionary }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dictionary.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dictionaries/1
  # PUT /dictionaries/1.xml
  def update
    @dictionary = current_user.dictionaries.find(params[:id])

    respond_to do |format|
      if @dictionary.update_attributes(params[:dictionary])
        format.html { redirect_to(@dictionary, :notice => 'Dictionary was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dictionary.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.xml
  def destroy
    @dictionary = current_user.dictionaries.find(params[:id])
    @dictionary.destroy

    respond_to do |format|
      format.html { redirect_to(dictionaries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.erb
<div class='block'>
  <%= form_for(@dictionary) do |f| %>
    <% if @dictionary.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

        <ul>
        <% @dictionary.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :desc %>
      <%= f.text_field :desc %>
    </p>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/dictionaries/edit.html.erb
<h1>Editing dictionary</h1>

<%= render 'form' %>

<% content_for :menu do %>
  <%= link_to 'Show', @dictionary %> |
  <%= link_to 'Back', dictionaries_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'Show', @dictionary %> |
  <%= link_to 'Back', dictionaries_path %>
<% end %>

app/views/dictionaries/index.html.erb
<h1>Listing dictionaries</h1>

<div id="content" class='block'>
  <h1 id="stats" style="float:left;"><%= @dictionaries.total_entries %> dictionaries</h1>
  <div style="clear:both;"></div>
  <%= will_paginate @dictionaries %>

  <table class='standard'>
    <thead>
      <tr id="header">
        <th class="">Name</th>
        <th class="">Description</th>
        <th colspan='3'>Actions</th>
      </tr>
    </thead>
    <% @dictionaries.each do |dic| %>
      <tr>
        <td>
          <strong><%= dic.name %></strong>
        </td>
        <td><%= dic.desc %></td>
        <td><%= link_to 'Show', dic %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dic) %></td>
        <td><%= link_to 'Destroy', dic, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>

  <%= will_paginate @dictionaries %>
</div>

<br />

<% content_for :menu do %>
  <%= link_to 'New Dictionary', new_dictionary_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'New Dictionary', new_dictionary_path %>
<% end %>

app/views/dictionaries/new.html.erb
<h1>New dictionary</h1>

<%= render 'form' %>

<% content_for :menu do %>
  <%= link_to 'Back', dictionaries_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'Back', dictionaries_path %>
<% end %>

app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Dictionary: <%= @dictionary.name %></h1>
<div id="content" class='block'>
  <h1 id="stats" style="float:left;"><%= @words.total_entries %> words</h1>
  <div style="clear:both;"></div>
  <%= will_paginate @words %>

  <table class='standard'>
    <thead>
      <tr id="header">
        <th class="">English</th>
        <th class="">Russian</th>
        <th colspan='2'>Actions</th>
        
      </tr>
    </thead>
    <% @words.each do |word| %>
      <tr>
        <td>
          <strong><%= word.word %></strong>
        </td>
        <td><%= link_to translate(word).html_safe, word %></td>

        <!-- <td><%= link_to 'Show', word %></td> -->
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  
<% content_for :menu do %>
  <%= link_to 'New Word', new_word_path(:word => {:dictionary_id => @dictionary.id}) %> |
  <%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
  <%= link_to 'Back', dictionaries_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'New Word', new_word_path(:word => {:dictionary_id => @dictionary.id}) %> |
  <%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
  <%= link_to 'Back', dictionaries_path %>
<% end %>