config/routes.rb
EnglishTrainer::Application.routes.draw do
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users

  resources :dictionaries

  resources :words

  root :to => "words#index"

end

app/models/word.rb
class Word < ActiveRecord::Base
  validates_presence_of :word
  belongs_to :dictionary
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]

  def index
    @words = Word.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    @user_session = UserSession.new
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @words }
    end
  end

  # GET /words/1
  # GET /words/1.xml
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/new
  # GET /words/new.xml
  def new
    @word = Word.new(params[:word])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.xml
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to( dictionary_path(@word.dictionary), :notice => 'Word was successfully created.') }
        format.xml  { render :xml => @word, :status => :created, :location => @word }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.xml
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to(@word, :notice => 'Word was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.xml
  def destroy
    @word = Word.find(params[:id])
    dic = @word.dictionary
    @word.destroy

    respond_to do |format|
      format.html { redirect_to(dictionary_url(dic)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def translate(word)
    tr = Google::Translate.new
    tr.translate :from => "en", :to => "ru", :text => word.word
  end
end

app/views/words/_form.html.erb
<div class='block'>
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :word %>
  <%= f.hidden_field :dictionary_id %>

  <div class="actions">
    <%= f.submit 'Add new word' %>
  </div>
<% end %>
</div>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>


<% content_for :menu do %>
  <%= link_to 'Show', @word %> |
  <%= link_to 'Back', words_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'Show', @word %> |
  <%= link_to 'Back', words_path %>
<% end %>

app/views/words/index.html.erb
<h1>Vocabulary</h1>

<div id="content" class='block'>
  <h1 id="stats" style="float:left;"><%= @words.total_entries %> words</h1>
  <div style="clear:both;"></div>
  <%= will_paginate @words %>

  <table class='standard'>
    <thead>
      <tr id="header">
        <th class="">English</th>
        <th class="">Russian</th>
        <% if current_user %><th colspan='2'>Actions</th><%end%>
      </tr>
    </thead>
    <% @words.each do |word| %>
      <tr>
        <td>
          <strong><%= word.word %></strong>
        </td>
        <td><%= link_to translate(word).html_safe, word %></td>
        <% if current_user %>
        <!-- <td><%= link_to 'Show', word %></td> -->
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= will_paginate @words %>
</div>
<br />

<% if current_user %>
  <% content_for :menu do %>
    <%= link_to 'New Word', new_word_path %> |
    <%= link_to 'Dictionaries', dictionaries_path %>
  <% end %>
  <% content_for :menu_bottom do %>
    <%= link_to 'New Word', new_word_path %> |
    <%= link_to 'Dictionaries', dictionaries_path %>
  <% end %>
<% else %>
  <% content_for :right_block do %>
    <h2>Login</h2>
    <%= render :partial => 'user_sessions/form' %>
  <% end %>
<% end %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<iframe width='790px' height='350px' src=<%= "http://www.google.com/dictionary?aq=f&langpair=en|ru&q=#{@word.word}&hl=en" %>>
</iframe><br/>

<% content_for :menu do %>
  <% if current_user %><%= link_to 'Edit', edit_word_path(@word) %> |<% end %>
  <%= link_to 'Back', words_path %>
<% end %>
<% content_for :menu_bottom do %>
  <% if current_user %><%= link_to 'Edit', edit_word_path(@word) %> |<% end %>
  <%= link_to 'Back', words_path %>
<% end %>