config/routes.rb
EnglishTrainer::Application.routes.draw do
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users

  resources :dictionaries

  resources :words

  root :to => "words#index"

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
      new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(dictionaries_path, :notice => 'Successfuly logged in.') }
        format.xml  { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<div class='block'>
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit 'Login', :style => 'float:right;' %>
  </div>
<% end %>
</div>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>


<% content_for :menu do %>
  <%= link_to 'Show', @user_session %> |
  <%= link_to 'Back', user_sessions_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'Show', @user_session %> |
  <%= link_to 'Back', user_sessions_path %>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<% content_for :menu do %>
  <%= link_to 'Back', root_path %>
<% end %>
<% content_for :menu_bottom do %>
  <%= link_to 'Back', root_path %>
<% end %>