config/routes.rb
EnglishTrainer::Application.routes.draw do
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users

  resources :dictionaries

  resources :words

  root :to => "words#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnglishTrainer</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class='menu'>
    <div class='left_nav'>
      <%= yield :menu %>
    </div>
    <div class='nav'>
    <% if current_user %>
      <%= link_to 'Edit profile', edit_user_path(:current) %> |
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Register', new_user_path %> |
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
    </div>
  </div>
  <div class='content'>
    <table class='main_table'>
      <tr>
        <td width='500px'>
          <%= yield %>
        </td>
        <td width='200px'>
          <div class='right_block'>
            <%= yield :right_block %>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div class='menu'>
    <div class='left_nav'>
      <%= yield :menu_bottom %>
    </div>
    <div class='nav'>
    <% if current_user %>
      <%= link_to 'Edit profile', edit_user_path(:current) %> |
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Register', new_user_path %> |
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
    </div>
  </div>
</body>
</html>